#! /usr/bin/expect

set CA_CN [lindex $argv 0]
set SERVER_CN [lindex $argv 1]
set OUT "out"
set SERVER_DIR "server"
set CA_DIR "ca"

spawn rm -rf ${OUT} ${CA_DIR} ${SERVER_DIR}

proc password {order cn} {
    spawn certstrap ${order} --cn ${cn}
    expect "*?(empty for no passphrase):*"
    send "\r"
    expect "*?passphrase again:*"
    send "\r"
    expect eof
}

password "init" ${CA_CN}

password "request-cert" ${SERVER_CN}

spawn certstrap sign ${SERVER_CN} --CA ${CA_CN}
expect eof

spawn rm -f ${OUT}/${SERVER_CN}.csr ${OUT}/${CA_CN}.crl
spawn mkdir ${SERVER_DIR}
spawn mv ${OUT}/${SERVER_CN}.crt ${OUT}/${SERVER_CN}.key ${SERVER_DIR}
spawn mv ${OUT} ${CA_DIR}
spawn chmod -R 755 .

expect eof
