#! /usr/bin/expect

set CA_CN [lindex $argv 0]
set SERVER_CN [lindex $argv 1]
set SERVER_IP [lindex $argv 2]
set OUT "out"

set CA_DIR "ca"
set SERVER_DIR "server"
set CLIENT_DIR "client"

spawn rm -rf ${OUT} ${CA_DIR} ${SERVER_DIR} ${CLIENT_DIR}

proc password {} {
    expect "*?(empty for no passphrase):*"
    send "\r"
    expect "*?passphrase again:*"
    send "\r"
    expect eof
}
spawn certstrap init --cn ${CA_CN}
password

spawn certstrap request-cert --ip ${SERVER_IP} --cn ${SERVER_CN}
password

spawn certstrap sign ${SERVER_CN} --CA ${CA_CN}
expect eof

spawn rm -f ${OUT}/${SERVER_CN}.csr ${OUT}/${CA_CN}.crl
spawn mkdir ${SERVER_DIR}
spawn mv ${OUT}/${SERVER_CN}.crt ${OUT}/${SERVER_CN}.key ${SERVER_DIR}
spawn mv ${OUT} ${CA_DIR}
spawn cp -r ${SERVER_DIR} ${CLIENT_DIR}
spawn chmod -R 755 .

expect eof
